spring:
    application:
        name: exo15
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/exo15db
        username: postgres
        password: postgres

    sql:
        init:
            mode: always
            platform: postgresql

  security:
    user:
      name: ignored
      password: ignored