spring:
  application:
    name: exo14
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/exo14db
    username: postgres
    password: postgres

  sql:
    init:
      mode: always
      platform: postgresql

  security:
    user:
    name: ignored
    password: ignored
