spring.application.name=exo12

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/exo12db
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

spring.sql.init.mode=always
spring.sql.init.platform=postgresql

server.port=8080